import type { Metadata } from "next";
import { Saira } from "next/font/google";
import "./globals.css";
import MainLayout from "@/components/Layout/MainLayout";

const font = Saira({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${font.variable} ${font.className} antialiased`}>
        <div className="min-h-screen w-full relative">
          <MainLayout>{children}</MainLayout>
        </div>
      </body>
    </html>
  );
}
